### PR TITLE
created a server folder

### PR DESCRIPTION
**Pull request by guoguoying2013**

### CODE REVIEW

**Comment by guoguoying2013** [comment]
@tbright7 @loganrosenlund37 @ecetino just testing, if you can see, let me know please.

**Review by tbright7 — APPROVED** [review]
Looks good!

**Comment by ecetino** [comment]
Looks good on my end. I'll probably end up using morgan now too. I forgot about it.

**Review by ecetino — APPROVED** [review]
Approved officially.

**Review by loganrosenlund37 — COMMENTED** [review]
Everything looks good and runs on my machine!

**Pull request merged**
